// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vspfwogjfhdijbnybjwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzcGZ3b2dqZmhkaWpibnliandiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDY2ODQsImV4cCI6MjA3MTAyMjY4NH0.S_u3Kt_p4GOsYagrWLTM7F8JMXeHAW5pzvzSBvgaVb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});